/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Platform */

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Platform
 * Method:    nativeGetString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_platform_Platform_nativeGetString
  (JNIEnv *env, jobject){
    return env->NewStringUTF("Hello from JNI !");
}

#ifdef __cplusplus
}
#endif
