/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Platform */

#ifndef _Included_Platform
#define _Included_Platform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Platform
 * Method:    nativeGetString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_platform_Platform_nativeGetString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
