/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class platform_Platform */

#ifndef _Included_platform_Platform
#define _Included_platform_Platform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     platform_Platform
 * Method:    nativeGetString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_platform_Platform_nativeGetString(JNIEnv *,
                                                                 jobject);

/*
 * Class:     platform_Platform
 * Method:    nativeUpdate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_platform_Platform_nativeUpdate(JNIEnv *, jobject);

/*
 * Class:     platform_Platform
 * Method:    nativeSum
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_platform_Platform_nativeSum(JNIEnv *, jobject,
                                                        jintArray);

/*
 * Class:     platform_Platform
 * Method:    nativeContact
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_platform_Platform_nativeContact(JNIEnv *,
                                                               jobject,
                                                               jobjectArray);

/*
 * Class:     platform_Platform
 * Method:    nativeMetaInfo
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_platform_Platform_nativeMetaInfo(JNIEnv *,
                                                                     jobject);

/*
 * Class:     platform_Platform
 * Method:    nativeException
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_platform_Platform_nativeException(JNIEnv *,
                                                              jobject);

#ifdef __cplusplus
}
#endif
#endif
